[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPAルーティング用のリダイレクト設定
# 存在しないページのみをindex.htmlにリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false